---
- hosts: "{{ host_group }}"
  vars_files:
    - secrets/vault.yaml
  roles: 
    - role: cifs_mount
      share_password: "{{ vault_share_password }}"
      share_username: "{{ vault_share_username }}"
      uid: "{{ vault_uid }}"
  become: yes
