---

- name: Install dependencies
  apt: name={{item}} state=installed
  with_items: "{{ apt-packages }}"
  when: ansible_facts['os_family'] == 'Debian'
  
- name: Install dependencies
  yum: package={{item}} state=installed 
  with_items: {{ yum-packages }}
  when: ansible_facts['os_family'] == 'RedHat'

- name: mount cifs share
  file:
    path: "{{ mount_point }}"
    state: directory
    mode: '0755'

- name: mount cifs
  mount:
    path: "{{ mount_point }}"
    state: directory
    src: "{{ share_name }}"
    fstype: cifs
    opts: username={{share_username}},password={{share_password}},uid={{uid}},iocharset=utf8,file_mode={{file_mode}},dir_mode={{dir_mode}},vers=3.0,mfsymlinks
    state: mounted
